#include <iostream.h>
#include <conio.h>
/*
Watermark:
RIFKI
*/
void main()
{
    clrscr();
                           /*
Watermark:
RIFKI
*/

    int gaji_guru[5];


    cout << "Masukkan gaji guru ke-1: Rp ";
    cin >> gaji_guru[0];

    cout << "Masukkan gaji guru ke-2: Rp ";
    cin >> gaji_guru[1];

    cout << "Masukkan gaji guru ke-3: Rp ";
    cin >> gaji_guru[2];

    cout << "Masukkan gaji guru ke-4: Rp ";
    cin >> gaji_guru[3];

    cout << "Masukkan gaji guru ke-5: Rp ";
    cin >> gaji_guru[4];


    cout << "Gaji Guru ke-1: Rp " << gaji_guru[0] << endl;
    cout << "Gaji Guru ke-2: Rp " << gaji_guru[1] << endl;
    cout << "Gaji Guru ke-3: Rp " << gaji_guru[2] << endl;
    cout << "Gaji Guru ke-4: Rp " << gaji_guru[3] << endl;
    cout << "Gaji Guru ke-5: Rp " << gaji_guru[4] << endl;

    getch();
}
             /*
Watermark:
RIFKI
*/
/*
Watermark:
RIFKI
*/
